---
kind: pipeline
type: docker
name: doc
clone:
  disable: true
steps:
  - name: skip_tls_clone
    image: plugins/git
    settings:
      depth: 10
      skip_verify: true
  - name: python
    image: python:3.10
    commands:
      - pip install poetry -i https://pypi.douban.com/simple
      - poetry export -f requirements.txt --output requirements.txt --without-hashes --with dev
      - pip install -r requirements.txt -i https://pypi.douban.com/simple
      - mkdocs build
      - tar -czvf wedoc.tar.gz ./site
  - name: scp files
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      port: 22
      key:
        from_secret: ssh_key
      target:
        - /data/www/wedoc
      source:
        - wedoc.tar.gz
  - name: untar file
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      port: 22
      key:
        from_secret: ssh_key
      script:
        - cd /data/www/wedoc
        - tar xf wedoc.tar.gz
        - rm -rf wedoc.tar.gz
  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    settings:
      token:
        from_secret: dingtalk_token
      type: markdown
      message_color: true
    when:
      status: [failure, success]
trigger:
  branch: master

---
kind: pipeline
type: docker
name: build and publish
clone:
  disable: true
steps:
  - name: skip_tls_clone
    image: plugins/git
    settings:
      depth: 10
      skip_verify: true
  - name: python
    image: python:3.10
    commands:
      - pip install poetry -i https://pypi.douban.com/simple
      - poetry build

  - name: pypi_publish
    image: plugins/pypi
    settings:
      username:
        from_secret: pypi_user
      password:
        from_secret: pypi_password
      skip_build: true
  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    settings:
      token:
        from_secret: dingtalk_token
      type: markdown
      message_color: true
    when:
      status: [failure, success]

trigger:
  branch: master
