site_name: Wedoc
site_url: https://wedoc.woni.link/
site_author: Wn0x00
repo_url: https://github.com/wn0x00/wedoc
repo_name: wn0x00/wedoc

copyright: Copyright &copy; 2023 - 2023 Wn0x00

theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.footer
    - navigation.path
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - 概述: index.md
  - 教程: guides.md
  - 指南:
      - 企业微信创建应用: weworkapp.md
  - FAQ: faq.md
  - 疑难解答: troubleshooting.md
  - 参考:
      - 参考文档: ref.md
      - API 接口: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python-requests.org/en/master/objects.inv
          options:
            do_something: true
